server:
  port: 8010
spring:
  application:
    name: consumer-movie-ribbon
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/